### ISSUE TITLE
[PE-D] Inconsistent in app behaviour vs app prompt

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-1/tp#317]
For addexpense, the app's command failure result message states that,
```
Cost should only contain numeric characters without spaces up to only 2 decimal places, and it should not be blank
```
which seems to suggest amount with more than 2 d.p. is invalid. Whereas in fact, it is considered as valid and rounded.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: JeffZincatz/ped#6

**Comment by marcuspeh** [comment]
@kheekheekhee `x * 100 % 1 == 0`
