### ISSUE TITLE
[PE-D] addexpense doesn't show error message when the group does not exist

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-1/tp#338]
![addexpense.jpg](https://raw.githubusercontent.com/LuoZhijie-tom/ped/main/files/c90660eb-2ff6-47be-9801-0d204f5f9950.jpg)

when the Catch up group does not exist, the app will not give error message when I press enter

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: LuoZhijie-tom/ped#9

**Comment by marcuspeh** [comment]
@kheekheekhee `addexpense gn/h n/David Li $/23 d/sdd`
