### ISSUE TITLE
Unclear User Guide 

### ISSUE THREAD

**Issue by chowsy** [AY2122S1-CS2103T-F13-1/tp#370]
![image](https://user-images.githubusercontent.com/81168896/140267933-3ae4a82f-36fb-43ce-89cc-f6b2c8c365dc.png)

**Comment by chowsy** [comment]
Not sure what the last bullet point means. 

Also, is it better to name the points numerically instead of having bullet points so that users can point out issue(s) straightaway?

**Comment by marcuspeh** [comment]
When you use this command, you will not be brought to the group page if you are currently viewing a different page
