### ISSUE TITLE
Bug 1 - No specific character limit for description 

### ISSUE THREAD

**Issue by chowsy** [AY2122S1-CS2103T-F13-1/tp#372]
![image](https://user-images.githubusercontent.com/81168896/140269835-10644fed-889d-4a86-8b3e-e330f24801fa.png)

**Comment by chowsy** [comment]
addexpense n/Marcus Peh gn/Holi $/100 d/for supper coz i am a glutton and i want to eat a lottttttt ex/Siyi 

Why does this not go through hmm

**Comment by marcuspeh** [comment]
![image](https://user-images.githubusercontent.com/54053213/140448782-0c217950-bb5b-4b4d-b570-5d1000910fe3.png)
@kheekheekhee Your error message for `Description` is wrong.
