### ISSUE TITLE
groupremovecontact doesn't seem to do anything?

### ISSUE THREAD

**Issue by Chesterwongz** [AY2122S1-CS2103T-F13-1/tp#402]
I ran the command `groupremovecontact gn/long group n/150` after viewing `expenses gn/long group` and nothing seemed to happen. 
seems like the difference is only seen in `contacts` and `groups`. Shouldn't all expenses of the contact be removed as well?

![image](https://user-images.githubusercontent.com/70138507/140524302-f56822a1-6886-463a-97cd-b3e0644ac27f.png)

**Comment by marcuspeh** [comment]
Nope, if it is deleted from a contact, the splitting of expenses incurred by the contact will not involve him.
